version: '3.1'
services:
  db:
    image: postgres:13.6
    restart: always
    env_file:
      - .env
    # volumes:
    #   - "db:/var/lib/postgresql/data"
    ports:
      - "5555:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 10
  backend:
    build: ./api
    entrypoint: /backend/api/entrypoint.sh
    context: /api
    dockerfile: Dockerfile
    environment:
        - DJANGO_SUPERUSER_USERNAME=admin
        - DJANGO_SUPERUSER_PASSWORD=admin1234
        - DJANGO_SUPERUSER_EMAIL=admin@twtrubiks.com
    
    ports:
     -"8000:8000"
    command: bash -c "python manage.py runserver 0.0.0.0:8080 
    && gunicorn library.wsgi -b 0.0.0.0:8080 "
    depends_on:
    - db
  frontend:

