version: '3.1'

services:
  db:
    image: postgres:13.6
    container_name: pg_db
    restart: always
    env_file:
      - .env
    volumes:
      - pg_vol:/var/lib/postgresql/data
    #ports:
    #  - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 10


  backend:
    build: .
    volumes:
      - .:/code
    #entrypoint: ./entrypoint.sh
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin1234
      - DJANGO_SUPERUSER_EMAIL=admin@twtrubiks.com
    ports:
      - 8000:8080
    command: bash -c "python manage.py makemigrations && python manage.py migrate &&  gunicorn smolathon.wsgi -b 0.0.0.0:8080 "
    depends_on:
      - db
volumes:
  pg_vol:
#  ngnix:
#   image: nginx:stable
#    ports:
#      - 8000:80
#   restart: always
#    volumes:
#      - ./#папка с фронтом
#    depends_on:
#      - db